; PlatformIO Project Configuration File

[platformio]
default_envs = esp32dev

[septic_common]
build_unflags =
  -std=gnu++11
build_flags =
  -std=gnu++17
  -Wall
  -Wextra

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  ${septic_common.build_flags}
  -DSEPTIC_TARGET_ESP32

[env:native]
platform = native
build_flags =
  ${septic_common.build_flags}
  -DSEPTIC_TARGET_NATIVE
test_framework = unity
test_build_src = no
